services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - ./bingosync-app:/app/bingosync-app
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "8000"

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    volumes:
      - ./bingosync-app:/app/bingosync-app
    expose:
      - "8888"

  nginx:
    image: nginx:stable
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./bingosync-app:/app/bingosync-app
    depends_on:
      - web
      - websocket

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: bingosync
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
