services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "8000"

  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    expose:
      - "8888"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web
      - websocket

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: bingosync
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
